name: Build, Publish Docker Image and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
          "GO_PORT=${{ secrets.GO_PORT }}"
          "JWT_SECRET=${{ secrets.JWT_SECRET }}"
          "AWS_REGION=${{ secrets.AWS_REGION }}"
          "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/exercise:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_SECRET_KEY }}
        script: |
          cd ${{ secrets.DIR }}
          git fetch
          git checkout main
          git pull origin main
        
          ./bin/migrate.sh

          docker compose pull
          docker compose up -d

